### ISSUE TITLE
Are there any write based load tests?

### ISSUE THREAD

**Issue by adamretter** [joewiz/hsg-test#9]
Looking at `https://github.com/joewiz/hsg-test/blob/master/src/test/jmeter/combined.jmx` all of the HTTP Methods appear to be `GET`. Are there any tests that perform writes to the database? and are there any tests that perform an interleaved concurrent series or reads and writes?

**Comment by wolfgangmm** [comment]
Right now the tests are read only because the cms part of the site has not been ported yet. It's rather easy to add some writes to the mix though, e.g. by randomly updating some of the large documents in /db/apps/frus/volumes, which corresponds to what editors will do in real life.

**Comment by adamretter** [comment]
@wolfgangmm Okay, I don't feel that I know anything about HSG. So I would not have enough knowledge to actually create real-world representative write tests for it. Perhaps you or @joewiz  will add some in the future...

**Comment by wolfgangmm** [comment]
Yes, we could add some. The read-only performance tests are quite comprehensive because they cover code written by different people over years, using different XQuery coding styles and libraries. Bottlenecks are easily visible as response times will quickly go through the ceiling, causing my machine to overheat and eventually die with a kernel panic ;-)

**Comment by adamretter** [comment]
@wolfgangmm heh that sounds fun. I was looking for tests that were more likely to cause liveness issues or deadlocks

**Comment by joewiz** [comment]
I'd be thrilled if the work that went into the hsg test suite could be used by the community.

**Comment by adamretter** [comment]
@joewiz Me too! :-)

**Comment by joewiz** [comment]
Closing, as the question has been answered. Adding write-based tests to this or another test suite sounds like a worthwhile idea.
